version: "3.9"

services:
  app:
    build: .
    ports:
      - "8100:8100"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8100"
    environment:
     - DB_ENGINE=django.db.backends.sqlite3
     - DB_NAME=/app/db.sqlite3




